[env]
TERM = "xterm-256color"

[shell]
program = "tmux"

[window]
padding.x = 1
padding.y = 1
decorations = "None"
opacity = 0.95

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
