import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml", "~/.local/share/omakub/defaults/alacritty.toml" ]

[window]

startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[scrolling]
multiplier = 10
